In [1]:
import numpy as np

In [11]:
m = np.random.rand(5,5)
print(m)
m[[0,4]] = m[[4,0]]
print("\t")
print(m)


[[0.3563638  0.46556428 0.87938226 0.85448241 0.77636822]
 [0.14311612 0.50283175 0.07893871 0.09661732 0.135672  ]
 [0.29302643 0.2947364  0.80854343 0.64468443 0.0240407 ]
 [0.6287951  0.41396194 0.04212009 0.80723759 0.56608701]
 [0.98146664 0.08009661 0.00266198 0.30981507 0.06354759]]
	
[[0.98146664 0.08009661 0.00266198 0.30981507 0.06354759]
 [0.14311612 0.50283175 0.07893871 0.09661732 0.135672  ]
 [0.29302643 0.2947364  0.80854343 0.64468443 0.0240407 ]
 [0.6287951  0.41396194 0.04212009 0.80723759 0.56608701]
 [0.3563638  0.46556428 0.87938226 0.85448241 0.77636822]]


In [22]:
arr = np.array([[1,2,3,4],[5,6,0,7]])
d = np.nonzero(arr)
print(arr[d])

[1 2 3 4 5 6 7]


In [27]:
arr = np.array([[1,2,3,4],[5,6,0,7]])
res = []
f = arr.flatten()
for i in f:
    if i == 0:
        continue
    else:
        res.append(i)

print(res)

[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7)]


In [30]:
arr = np.array([[1,2,3,4],[5,6,0,7]])
nz = arr[np.any(arr!=0, axis = 1)]
nz

array([[1, 2, 3, 4],
       [5, 6, 0, 7]])

In [33]:
a = np.array([1.00000000+0.j, 0.70710678+0.70710678j])
print('real', a.real)
print('imaginary', a.imag)

real [1.         0.70710678]
imaginary [0.         0.70710678]


In [34]:
a = np.array([1.00000000+0.j, 0.70710678+0.70710678j])
reall = [np.real(n) for n in a]
imagg = [np.imag(n) for n in a]
print(reall, imagg)

[np.float64(1.0), np.float64(0.70710678)] [np.float64(0.0), np.float64(0.70710678)]


In [41]:
a = np.array([10,10,20,20,30,30])
remove_dup = []
for i in range(len(a)):
    if a[i] not in remove_dup:
        remove_dup.append(a[i])
print(remove_dup)

[np.int64(10), np.int64(20), np.int64(30)]


In [40]:
a = np.array([10,10,20,20,30,30])
rem = np.unique(a)
rem

array([10, 20, 30])

In [43]:
a = np.array([10,10,20,20,30,30])
for i in range(len(a)):
    print(a[i])


10
10
20
20
30
30


In [44]:
len(a)

6

In [49]:
a = np.array([10,10,20,20,30,30])

remove_dup = []

for i in range(len(a)):
    for j in range(i+1,len(a)):
        if a[i] == a[j]:
            remove_dup.append(a[j])

print(remove_dup)

[np.int64(10), np.int64(20), np.int64(30)]


In [50]:
a = np.random.rand(3,3,3)
a

array([[[0.37469616, 0.13436506, 0.68497878],
        [0.16342318, 0.45475428, 0.84260773],
        [0.84000384, 0.12079802, 0.22439961]],

       [[0.72078697, 0.35931421, 0.93979265],
        [0.150426  , 0.42226258, 0.58286532],
        [0.51334426, 0.18485582, 0.03588847]],

       [[0.92586965, 0.66017821, 0.51317765],
        [0.88390062, 0.82975959, 0.92074526],
        [0.18594705, 0.99867459, 0.50092109]]])

In [4]:
import numpy as np
#a = np.array([7,6,5,6,1,2,3])
a = np.random.rand(10)
print('Before Sorting,', a)
for i in range(len(a)):
    for j in range(0, len(a)-i-1):
        if a[j] > a[j+1]:
            a[j] , a[j+1] = a[j+1] , a[j]


print('After Sorting', a)

Before Sorting, [0.34064048 0.71169032 0.0518584  0.70088037 0.19218108 0.29322675
 0.39945774 0.23480106 0.35284879 0.36983459]
After Sorting [0.0518584  0.19218108 0.23480106 0.29322675 0.34064048 0.35284879
 0.36983459 0.39945774 0.70088037 0.71169032]


In [5]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
print(np.array_equal(a,b))

False


In [6]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(np.array_equal(a,b))

True


In [11]:
a = np.array([[10 ,40],[30 ,20]])
print(a)
print(np.sort((a), axis = 1))
print(np.sort((a), axis = 0))
print(a.flatten())


[[10 40]
 [30 20]]
[[10 40]
 [20 30]]
[[10 20]
 [30 40]]
[10 40 30 20]


In [15]:
a = np.array([[-1.6 ,-1.5 ,-0.3 ,0.1, 1.4, 1.8, 2. ]])
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))

[[-2. -2. -1.  0.  1.  1.  2.]]
[[-1. -1. -0.  1.  2.  2.  2.]]
[[-1. -1. -0.  0.  1.  1.  2.]]


In [19]:
import calendar
yy = 2017
dd = 3
print(calendar.month(yy,dd))

     March 2017
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30 31



In [24]:
from datetime import timedelta, datetime
start_date = datetime(2026,1,1,0,0)
datetime_object = [start_date+timedelta(hours = i) for i in range(24)]
datetime_object

[datetime.datetime(2026, 1, 1, 0, 0),
 datetime.datetime(2026, 1, 1, 1, 0),
 datetime.datetime(2026, 1, 1, 2, 0),
 datetime.datetime(2026, 1, 1, 3, 0),
 datetime.datetime(2026, 1, 1, 4, 0),
 datetime.datetime(2026, 1, 1, 5, 0),
 datetime.datetime(2026, 1, 1, 6, 0),
 datetime.datetime(2026, 1, 1, 7, 0),
 datetime.datetime(2026, 1, 1, 8, 0),
 datetime.datetime(2026, 1, 1, 9, 0),
 datetime.datetime(2026, 1, 1, 10, 0),
 datetime.datetime(2026, 1, 1, 11, 0),
 datetime.datetime(2026, 1, 1, 12, 0),
 datetime.datetime(2026, 1, 1, 13, 0),
 datetime.datetime(2026, 1, 1, 14, 0),
 datetime.datetime(2026, 1, 1, 15, 0),
 datetime.datetime(2026, 1, 1, 16, 0),
 datetime.datetime(2026, 1, 1, 17, 0),
 datetime.datetime(2026, 1, 1, 18, 0),
 datetime.datetime(2026, 1, 1, 19, 0),
 datetime.datetime(2026, 1, 1, 20, 0),
 datetime.datetime(2026, 1, 1, 21, 0),
 datetime.datetime(2026, 1, 1, 22, 0),
 datetime.datetime(2026, 1, 1, 23, 0)]

In [25]:
a1 = np.array([['Python' ,'PHP']])
a2 = np.array([[' Java' ,' C++']])
print(a1+a2)

[['Python Java' 'PHP C++']]


In [30]:
r = []
for x,y in zip(a1,a2):
    r.append(x + ' '+ y)

print(r)   

[array(['Python  Java', 'PHP  C++'], dtype='<U12')]
